name: DailyFit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_sign_in: ^6.3.0
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.2
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  http: ^1.2.1
  google_fonts: ^6.2.1
  #  permission_handler: ^11.3.0
  #  health: ^13.1.1
  intl: ^0.19.0
#  device_info_plus: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  flutter_signin_button: ^2.0.0
  firebase_core: ^2.30.0 # Moved from dev_dependencies
  firebase_auth: ^4.17.3 # Moved from dev_dependencies
  cloud_firestore: ^4.15.3 # Moved from dev_dependencies
  firebase_storage: ^11.7.3 # Moved from dev_dependencies
  #  google_maps_flutter: ^2.12.3 # MOVED HERE from dev_dependencies
  #  location: ^6.0.2 # Moved from dev_dependencies
  firebase_app_check: ^0.2.1+6 # Moved from dev_dependencies


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/step_data.json
    - assets/data/mock_app_data.json